version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    command: redis-server --requirepass $password --appendonly yes
    volumes:
      - ./volumes/redis:/data:rw,z
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - pepa-network

# Docker Networks
networks:
  # All container connect in a network
  pepa-network:
    driver: bridge
